<?php

/**
 * Cozy.ValueObjects
 *
 * (c) Nestor Picado <info@nestorpicado.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cozy\ValueObjects\Repositories;

use Cozy\ValueObjects\Language;
use Generator;
use InvalidArgumentException;

class LanguageRepository
{
    private static array $storage = [
        'alpha2' => [
            'ab' => [
                'name_en' => 'Abkhazian',
                'name' => 'аҧсуа бызшәа, аҧсшәа',
                'alpha2' => 'ab',
                'alpha3' => 'abk',
            ],
            'aa' => [
                'name_en' => 'Afar',
                'name' => 'Afaraf',
                'alpha2' => 'aa',
                'alpha3' => 'aar',
            ],
            'af' => [
                'name_en' => 'Afrikaans',
                'name' => 'Afrikaans',
                'alpha2' => 'af',
                'alpha3' => 'afr',
            ],
            'ak' => [
                'name_en' => 'Akan',
                'name' => 'Akan',
                'alpha2' => 'ak',
                'alpha3' => 'aka',
            ],
            'sq' => [
                'name_en' => 'Albanian',
                'name' => 'Shqip',
                'alpha2' => 'sq',
                'alpha3' => 'sqi',
            ],
            'am' => [
                'name_en' => 'Amharic',
                'name' => 'አማርኛ',
                'alpha2' => 'am',
                'alpha3' => 'amh',
            ],
            'ar' => [
                'name_en' => 'Arabic',
                'name' => 'العربية',
                'alpha2' => 'ar',
                'alpha3' => 'ara',
            ],
            'an' => [
                'name_en' => 'Aragonese',
                'name' => 'aragonés',
                'alpha2' => 'an',
                'alpha3' => 'arg',
            ],
            'hy' => [
                'name_en' => 'Armenian',
                'name' => 'Հայերեն',
                'alpha2' => 'hy',
                'alpha3' => 'hye',
            ],
            'as' => [
                'name_en' => 'Assamese',
                'name' => 'অসমীয়া',
                'alpha2' => 'as',
                'alpha3' => 'asm',
            ],
            'av' => [
                'name_en' => 'Avaric',
                'name' => 'авар мацӀ, магӀарул мацӀ',
                'alpha2' => 'av',
                'alpha3' => 'ava',
            ],
            'ae' => [
                'name_en' => 'Avestan',
                'name' => 'avesta',
                'alpha2' => 'ae',
                'alpha3' => 'ave',
            ],
            'ay' => [
                'name_en' => 'Aymara',
                'name' => 'aymar aru',
                'alpha2' => 'ay',
                'alpha3' => 'aym',
            ],
            'az' => [
                'name_en' => 'Azerbaijani',
                'name' => 'azərbaycan dili, تۆرکجه',
                'alpha2' => 'az',
                'alpha3' => 'aze',
            ],
            'bm' => [
                'name_en' => 'Bambara',
                'name' => 'bamanankan',
                'alpha2' => 'bm',
                'alpha3' => 'bam',
            ],
            'ba' => [
                'name_en' => 'Bashkir',
                'name' => 'башҡорт теле',
                'alpha2' => 'ba',
                'alpha3' => 'bak',
            ],
            'eu' => [
                'name_en' => 'Basque',
                'name' => 'euskara, euskera',
                'alpha2' => 'eu',
                'alpha3' => 'eus',
            ],
            'be' => [
                'name_en' => 'Belarusian',
                'name' => 'беларуская мова',
                'alpha2' => 'be',
                'alpha3' => 'bel',
            ],
            'bn' => [
                'name_en' => 'Bengali',
                'name' => 'বাংলা',
                'alpha2' => 'bn',
                'alpha3' => 'ben',
            ],
            'bh' => [
                'name_en' => 'Bihari languages',
                'name' => 'भोजपुरी',
                'alpha2' => 'bh',
                'alpha3' => 'bih',
            ],
            'bi' => [
                'name_en' => 'Bislama',
                'name' => 'Bislama',
                'alpha2' => 'bi',
                'alpha3' => 'bis',
            ],
            'bs' => [
                'name_en' => 'Bosnian',
                'name' => 'bosanski jezik',
                'alpha2' => 'bs',
                'alpha3' => 'bos',
            ],
            'br' => [
                'name_en' => 'Breton',
                'name' => 'brezhoneg',
                'alpha2' => 'br',
                'alpha3' => 'bre',
            ],
            'bg' => [
                'name_en' => 'Bulgarian',
                'name' => 'български език',
                'alpha2' => 'bg',
                'alpha3' => 'bul',
            ],
            'my' => [
                'name_en' => 'Burmese',
                'name' => 'ဗမာစာ',
                'alpha2' => 'my',
                'alpha3' => 'mya',
            ],
            'ca' => [
                'name_en' => 'Catalan , Valencian',
                'name' => 'català, valencià',
                'alpha2' => 'ca',
                'alpha3' => 'cat',
            ],
            'ch' => [
                'name_en' => 'Chamorro',
                'name' => 'Chamoru',
                'alpha2' => 'ch',
                'alpha3' => 'cha',
            ],
            'ce' => [
                'name_en' => 'Chechen',
                'name' => 'нохчийн мотт',
                'alpha2' => 'ce',
                'alpha3' => 'che',
            ],
            'ny' => [
                'name_en' => 'Chichewa , Chewa, Nyanja',
                'name' => 'chiCheŵa, chinyanja',
                'alpha2' => 'ny',
                'alpha3' => 'nya',
            ],
            'zh' => [
                'name_en' => 'Chinese',
                'name' => '中文 (Zhōngwén ], 汉语 , 漢語',
                'alpha2' => 'zh',
                'alpha3' => 'zho',
            ],
            'cv' => [
                'name_en' => 'Chuvash',
                'name' => 'чӑваш чӗлхи',
                'alpha2' => 'cv',
                'alpha3' => 'chv',
            ],
            'kw' => [
                'name_en' => 'Cornish',
                'name' => 'Kernewek',
                'alpha2' => 'kw',
                'alpha3' => 'cor',
            ],
            'co' => [
                'name_en' => 'Corsican',
                'name' => 'corsu, lingua corsa',
                'alpha2' => 'co',
                'alpha3' => 'cos',
            ],
            'cr' => [
                'name_en' => 'Cree',
                'name' => 'ᓀᐦᐃᔭᐍᐏᐣ',
                'alpha2' => 'cr',
                'alpha3' => 'cre',
            ],
            'hr' => [
                'name_en' => 'Croatian',
                'name' => 'hrvatski jezik',
                'alpha2' => 'hr',
                'alpha3' => 'hrv',
            ],
            'cs' => [
                'name_en' => 'Czech',
                'name' => 'čeština, český jazyk',
                'alpha2' => 'cs',
                'alpha3' => 'ces',
            ],
            'da' => [
                'name_en' => 'Danish',
                'name' => 'dansk',
                'alpha2' => 'da',
                'alpha3' => 'dan',
            ],
            'dv' => [
                'name_en' => 'Divehi , Dhivehi, Maldivian',
                'name' => 'ދިވެހި',
                'alpha2' => 'dv',
                'alpha3' => 'div',
            ],
            'nl' => [
                'name_en' => 'Dutch , Flemish',
                'name' => 'Nederlands, Vlaams',
                'alpha2' => 'nl',
                'alpha3' => 'nld',
            ],
            'dz' => [
                'name_en' => 'Dzongkha',
                'name' => 'རྫོང་ཁ',
                'alpha2' => 'dz',
                'alpha3' => 'dzo',
            ],
            'en' => [
                'name_en' => 'English',
                'name' => 'English',
                'alpha2' => 'en',
                'alpha3' => 'eng',
            ],
            'eo' => [
                'name_en' => 'Esperanto',
                'name' => 'Esperanto',
                'alpha2' => 'eo',
                'alpha3' => 'epo',
            ],
            'et' => [
                'name_en' => 'Estonian',
                'name' => 'eesti, eesti keel',
                'alpha2' => 'et',
                'alpha3' => 'est',
            ],
            'ee' => [
                'name_en' => 'Ewe',
                'name' => 'Eʋegbe',
                'alpha2' => 'ee',
                'alpha3' => 'ewe',
            ],
            'fo' => [
                'name_en' => 'Faroese',
                'name' => 'føroyskt',
                'alpha2' => 'fo',
                'alpha3' => 'fao',
            ],
            'fj' => [
                'name_en' => 'Fijian',
                'name' => 'vosa Vakaviti',
                'alpha2' => 'fj',
                'alpha3' => 'fij',
            ],
            'fi' => [
                'name_en' => 'Finnish',
                'name' => 'Suomi, suomen kieli',
                'alpha2' => 'fi',
                'alpha3' => 'fin',
            ],
            'fr' => [
                'name_en' => 'French',
                'name' => 'Français, langue française',
                'alpha2' => 'fr',
                'alpha3' => 'fra',
            ],
            'ff' => [
                'name_en' => 'Fulah',
                'name' => 'Fulfulde, Pulaar, Pular',
                'alpha2' => 'ff',
                'alpha3' => 'ful',
            ],
            'gl' => [
                'name_en' => 'Galician',
                'name' => 'Galego',
                'alpha2' => 'gl',
                'alpha3' => 'glg',
            ],
            'ka' => [
                'name_en' => 'Georgian',
                'name' => 'ქართული',
                'alpha2' => 'ka',
                'alpha3' => 'kat',
            ],
            'de' => [
                'name_en' => 'German',
                'name' => 'Deutsch',
                'alpha2' => 'de',
                'alpha3' => 'deu',
            ],
            'el' => [
                'name_en' => 'Greek , Modern (1453–)',
                'name' => 'ελληνικά',
                'alpha2' => 'el',
                'alpha3' => 'ell',
            ],
            'gn' => [
                'name_en' => 'Guarani',
                'name' => 'Avañe\'ẽ',
                'alpha2' => 'gn',
                'alpha3' => 'grn',
            ],
            'gu' => [
                'name_en' => 'Gujarati',
                'name' => 'ગુજરાતી',
                'alpha2' => 'gu',
                'alpha3' => 'guj',
            ],
            'ht' => [
                'name_en' => 'Haitian , Haitian Creole',
                'name' => 'Kreyòl ayisyen',
                'alpha2' => 'ht',
                'alpha3' => 'hat',
            ],
            'ha' => [
                'name_en' => 'Hausa',
                'name' => '(Hausa) هَوُسَ',
                'alpha2' => 'ha',
                'alpha3' => 'hau',
            ],
            'he' => [
                'name_en' => 'Hebrew',
                'name' => 'עברית',
                'alpha2' => 'he',
                'alpha3' => 'heb',
            ],
            'hz' => [
                'name_en' => 'Herero',
                'name' => 'Otjiherero',
                'alpha2' => 'hz',
                'alpha3' => 'her',
            ],
            'hi' => [
                'name_en' => 'Hindi',
                'name' => 'हिन्दी, हिंदी',
                'alpha2' => 'hi',
                'alpha3' => 'hin',
            ],
            'ho' => [
                'name_en' => 'Hiri Motu',
                'name' => 'Hiri Motu',
                'alpha2' => 'ho',
                'alpha3' => 'hmo',
            ],
            'hu' => [
                'name_en' => 'Hungarian',
                'name' => 'magyar',
                'alpha2' => 'hu',
                'alpha3' => 'hun',
            ],
            'ia' => [
                'name_en' => 'Interlingua (International Auxiliary Language Association)',
                'name' => 'Interlingua',
                'alpha2' => 'ia',
                'alpha3' => 'ina',
            ],
            'id' => [
                'name_en' => 'Indonesian',
                'name' => 'Bahasa Indonesia',
                'alpha2' => 'id',
                'alpha3' => 'ind',
            ],
            'ie' => [
                'name_en' => 'Interlingue , Occidental',
                'name' => '(originally:) Occidental , (after WWII:) Interlingue',
                'alpha2' => 'ie',
                'alpha3' => 'ile',
            ],
            'ga' => [
                'name_en' => 'Irish',
                'name' => 'Gaeilge',
                'alpha2' => 'ga',
                'alpha3' => 'gle',
            ],
            'ig' => [
                'name_en' => 'Igbo',
                'name' => 'Asụsụ Igbo',
                'alpha2' => 'ig',
                'alpha3' => 'ibo',
            ],
            'ik' => [
                'name_en' => 'Inupiaq',
                'name' => 'Iñupiaq, Iñupiatun',
                'alpha2' => 'ik',
                'alpha3' => 'ipk',
            ],
            'io' => [
                'name_en' => 'Ido',
                'name' => 'Ido',
                'alpha2' => 'io',
                'alpha3' => 'ido',
            ],
            'is' => [
                'name_en' => 'Icelandic',
                'name' => 'Íslenska',
                'alpha2' => 'is',
                'alpha3' => 'isl',
            ],
            'it' => [
                'name_en' => 'Italian',
                'name' => 'Italiano',
                'alpha2' => 'it',
                'alpha3' => 'ita',
            ],
            'iu' => [
                'name_en' => 'Inuktitut',
                'name' => 'ᐃᓄᒃᑎᑐᑦ',
                'alpha2' => 'iu',
                'alpha3' => 'iku',
            ],
            'ja' => [
                'name_en' => 'Japanese',
                'name' => '日本語 ( にほんご )',
                'alpha2' => 'ja',
                'alpha3' => 'jpn',
            ],
            'jv' => [
                'name_en' => 'Javanese',
                'name' => 'ꦧꦱꦗꦮ, Basa Jawa',
                'alpha2' => 'jv',
                'alpha3' => 'jav',
            ],
            'kl' => [
                'name_en' => 'Kalaallisut , Greenlandic',
                'name' => 'kalaallisut, kalaallit oqaasii',
                'alpha2' => 'kl',
                'alpha3' => 'kal',
            ],
            'kn' => [
                'name_en' => 'Kannada',
                'name' => 'ಕನ್ನಡ',
                'alpha2' => 'kn',
                'alpha3' => 'kan',
            ],
            'kr' => [
                'name_en' => 'Kanuri',
                'name' => 'Kanuri',
                'alpha2' => 'kr',
                'alpha3' => 'kau',
            ],
            'ks' => [
                'name_en' => 'Kashmiri',
                'name' => 'कश्मीरी , كشميري ‎',
                'alpha2' => 'ks',
                'alpha3' => 'kas',
            ],
            'kk' => [
                'name_en' => 'Kazakh',
                'name' => 'қазақ тілі',
                'alpha2' => 'kk',
                'alpha3' => 'kaz',
            ],
            'km' => [
                'name_en' => 'Central Khmer',
                'name' => 'ខ្មែរ, ខេមរភាសា, ភាសាខ្មែរ',
                'alpha2' => 'km',
                'alpha3' => 'khm',
            ],
            'ki' => [
                'name_en' => 'Kikuyu , Gikuyu',
                'name' => 'Gĩkũyũ',
                'alpha2' => 'ki',
                'alpha3' => 'kik',
            ],
            'rw' => [
                'name_en' => 'Kinyarwanda',
                'name' => 'Ikinyarwanda',
                'alpha2' => 'rw',
                'alpha3' => 'kin',
            ],
            'ky' => [
                'name_en' => 'Kirghiz , Kyrgyz',
                'name' => 'Кыргызча, Кыргыз тили',
                'alpha2' => 'ky',
                'alpha3' => 'kir',
            ],
            'kv' => [
                'name_en' => 'Komi',
                'name' => 'коми кыв',
                'alpha2' => 'kv',
                'alpha3' => 'kom',
            ],
            'kg' => [
                'name_en' => 'Kongo',
                'name' => 'Kikongo',
                'alpha2' => 'kg',
                'alpha3' => 'kon',
            ],
            'ko' => [
                'name_en' => 'Korean',
                'name' => '한국어',
                'alpha2' => 'ko',
                'alpha3' => 'kor',
            ],
            'ku' => [
                'name_en' => 'Kurdish',
                'name' => 'Kurdî , کوردی ‎',
                'alpha2' => 'ku',
                'alpha3' => 'kur',
            ],
            'kj' => [
                'name_en' => 'Kuanyama , Kwanyama',
                'name' => 'Kuanyama',
                'alpha2' => 'kj',
                'alpha3' => 'kua',
            ],
            'la' => [
                'name_en' => 'Latin',
                'name' => 'latine, lingua latina',
                'alpha2' => 'la',
                'alpha3' => 'lat',
            ],
            'lb' => [
                'name_en' => 'Luxembourgish , Letzeburgesch',
                'name' => 'Lëtzebuergesch',
                'alpha2' => 'lb',
                'alpha3' => 'ltz',
            ],
            'lg' => [
                'name_en' => 'Ganda',
                'name' => 'Luganda',
                'alpha2' => 'lg',
                'alpha3' => 'lug',
            ],
            'li' => [
                'name_en' => 'Limburgan , Limburger, Limburgish',
                'name' => 'Limburgs',
                'alpha2' => 'li',
                'alpha3' => 'lim',
            ],
            'ln' => [
                'name_en' => 'Lingala',
                'name' => 'Lingála',
                'alpha2' => 'ln',
                'alpha3' => 'lin',
            ],
            'lo' => [
                'name_en' => 'Lao',
                'name' => 'ພາສາລາວ',
                'alpha2' => 'lo',
                'alpha3' => 'lao',
            ],
            'lt' => [
                'name_en' => 'Lithuanian',
                'name' => 'lietuvių kalba',
                'alpha2' => 'lt',
                'alpha3' => 'lit',
            ],
            'lu' => [
                'name_en' => 'Luba-Katanga',
                'name' => 'Kiluba',
                'alpha2' => 'lu',
                'alpha3' => 'lub',
            ],
            'lv' => [
                'name_en' => 'Latvian',
                'name' => 'latviešu valoda',
                'alpha2' => 'lv',
                'alpha3' => 'lav',
            ],
            'gv' => [
                'name_en' => 'Manx',
                'name' => 'Gaelg, Gailck',
                'alpha2' => 'gv',
                'alpha3' => 'glv',
            ],
            'mk' => [
                'name_en' => 'Macedonian',
                'name' => 'македонски јазик',
                'alpha2' => 'mk',
                'alpha3' => 'mkd',
            ],
            'mg' => [
                'name_en' => 'Malagasy',
                'name' => 'fiteny malagasy',
                'alpha2' => 'mg',
                'alpha3' => 'mlg',
            ],
            'ms' => [
                'name_en' => 'Malay',
                'name' => 'Bahasa Melayu , بهاس ملايو ‎',
                'alpha2' => 'ms',
                'alpha3' => 'msa',
            ],
            'ml' => [
                'name_en' => 'Malayalam',
                'name' => 'മലയാളം',
                'alpha2' => 'ml',
                'alpha3' => 'mal',
            ],
            'mt' => [
                'name_en' => 'Maltese',
                'name' => 'Malti',
                'alpha2' => 'mt',
                'alpha3' => 'mlt',
            ],
            'mi' => [
                'name_en' => 'Maori',
                'name' => 'te reo Māori',
                'alpha2' => 'mi',
                'alpha3' => 'mri',
            ],
            'mr' => [
                'name_en' => 'Marathi',
                'name' => 'मराठी',
                'alpha2' => 'mr',
                'alpha3' => 'mar',
            ],
            'mh' => [
                'name_en' => 'Marshallese',
                'name' => 'Kajin M̧ajeļ',
                'alpha2' => 'mh',
                'alpha3' => 'mah',
            ],
            'mn' => [
                'name_en' => 'Mongolian',
                'name' => 'Монгол хэл',
                'alpha2' => 'mn',
                'alpha3' => 'mon',
            ],
            'na' => [
                'name_en' => 'Nauru',
                'name' => 'Dorerin Naoero',
                'alpha2' => 'na',
                'alpha3' => 'nau',
            ],
            'nv' => [
                'name_en' => 'Navajo , Navaho',
                'name' => 'Diné bizaad',
                'alpha2' => 'nv',
                'alpha3' => 'nav',
            ],
            'nd' => [
                'name_en' => 'North Ndebele',
                'name' => 'isiNdebele',
                'alpha2' => 'nd',
                'alpha3' => 'nde',
            ],
            'ne' => [
                'name_en' => 'Nepali',
                'name' => 'नेपाली',
                'alpha2' => 'ne',
                'alpha3' => 'nep',
            ],
            'ng' => [
                'name_en' => 'Ndonga',
                'name' => 'Owambo',
                'alpha2' => 'ng',
                'alpha3' => 'ndo',
            ],
            'nb' => [
                'name_en' => 'Norwegian Bokmål',
                'name' => 'Norsk Bokmål',
                'alpha2' => 'nb',
                'alpha3' => 'nob',
            ],
            'nn' => [
                'name_en' => 'Norwegian Nynorsk',
                'name' => 'Norsk Nynorsk',
                'alpha2' => 'nn',
                'alpha3' => 'nno',
            ],
            'no' => [
                'name_en' => 'Norwegian',
                'name' => 'Norsk',
                'alpha2' => 'no',
                'alpha3' => 'nor',
            ],
            'ii' => [
                'name_en' => 'Sichuan Yi , Nuosu',
                'name' => 'ꆈꌠ꒿ Nuosuhxop',
                'alpha2' => 'ii',
                'alpha3' => 'iii',
            ],
            'nr' => [
                'name_en' => 'South Ndebele',
                'name' => 'isiNdebele',
                'alpha2' => 'nr',
                'alpha3' => 'nbl',
            ],
            'oc' => [
                'name_en' => 'Occitan',
                'name' => 'occitan, lenga d\'òc',
                'alpha2' => 'oc',
                'alpha3' => 'oci',
            ],
            'oj' => [
                'name_en' => 'Ojibwa',
                'name' => 'ᐊᓂᔑᓈᐯᒧᐎᓐ',
                'alpha2' => 'oj',
                'alpha3' => 'oji',
            ],
            'cu' => [
                'name_en' => 'Church Slavic , Old Slavonic, Church Slavonic, Old Bulgarian, Old Church Slavonic',
                'name' => 'ѩзыкъ словѣньскъ',
                'alpha2' => 'cu',
                'alpha3' => 'chu',
            ],
            'om' => [
                'name_en' => 'Oromo',
                'name' => 'Afaan Oromoo',
                'alpha2' => 'om',
                'alpha3' => 'orm',
            ],
            'or' => [
                'name_en' => 'Oriya',
                'name' => 'ଓଡ଼ିଆ',
                'alpha2' => 'or',
                'alpha3' => 'ori',
            ],
            'os' => [
                'name_en' => 'Ossetian , Ossetic',
                'name' => 'ирон æвзаг',
                'alpha2' => 'os',
                'alpha3' => 'oss',
            ],
            'pa' => [
                'name_en' => 'Punjabi , Panjabi',
                'name' => 'ਪੰਜਾਬੀ , پنجابی ‎',
                'alpha2' => 'pa',
                'alpha3' => 'pan',
            ],
            'pi' => [
                'name_en' => 'Pali',
                'name' => 'पालि, पाळि',
                'alpha2' => 'pi',
                'alpha3' => 'pli',
            ],
            'fa' => [
                'name_en' => 'Persian',
                'name' => 'فارسی',
                'alpha2' => 'fa',
                'alpha3' => 'fas',
            ],
            'pl' => [
                'name_en' => 'Polish',
                'name' => 'język polski, polszczyzna',
                'alpha2' => 'pl',
                'alpha3' => 'pol',
            ],
            'ps' => [
                'name_en' => 'Pashto , Pushto',
                'name' => 'پښتو',
                'alpha2' => 'ps',
                'alpha3' => 'pus',
            ],
            'pt' => [
                'name_en' => 'Portuguese',
                'name' => 'Português',
                'alpha2' => 'pt',
                'alpha3' => 'por',
            ],
            'qu' => [
                'name_en' => 'Quechua',
                'name' => 'Runa Simi, Kichwa',
                'alpha2' => 'qu',
                'alpha3' => 'que',
            ],
            'rm' => [
                'name_en' => 'Romansh',
                'name' => 'Rumantsch Grischun',
                'alpha2' => 'rm',
                'alpha3' => 'roh',
            ],
            'rn' => [
                'name_en' => 'Rundi',
                'name' => 'Ikirundi',
                'alpha2' => 'rn',
                'alpha3' => 'run',
            ],
            'ro' => [
                'name_en' => 'Romanian , Moldavian, Moldovan',
                'name' => 'Română',
                'alpha2' => 'ro',
                'alpha3' => 'ron',
            ],
            'ru' => [
                'name_en' => 'Russian',
                'name' => 'русский',
                'alpha2' => 'ru',
                'alpha3' => 'rus',
            ],
            'sa' => [
                'name_en' => 'Sanskrit',
                'name' => 'संस्कृतम् , 𑌸𑌂𑌸𑍍𑌕𑍃𑌤𑌮𑍍',
                'alpha2' => 'sa',
                'alpha3' => 'san',
            ],
            'sc' => [
                'name_en' => 'Sardinian',
                'name' => 'sardu',
                'alpha2' => 'sc',
                'alpha3' => 'srd',
            ],
            'sd' => [
                'name_en' => 'Sindhi',
                'name' => 'सिन्धी , سنڌي، سندھی ‎',
                'alpha2' => 'sd',
                'alpha3' => 'snd',
            ],
            'se' => [
                'name_en' => 'Northern Sami',
                'name' => 'Davvisámegiella',
                'alpha2' => 'se',
                'alpha3' => 'sme',
            ],
            'sm' => [
                'name_en' => 'Samoan',
                'name' => 'gagana fa\'a Samoa',
                'alpha2' => 'sm',
                'alpha3' => 'smo',
            ],
            'sg' => [
                'name_en' => 'Sango',
                'name' => 'yângâ tî sängö',
                'alpha2' => 'sg',
                'alpha3' => 'sag',
            ],
            'sr' => [
                'name_en' => 'Serbian',
                'name' => 'српски језик',
                'alpha2' => 'sr',
                'alpha3' => 'srp',
            ],
            'gd' => [
                'name_en' => 'Gaelic , Scottish Gaelic',
                'name' => 'Gàidhlig',
                'alpha2' => 'gd',
                'alpha3' => 'gla',
            ],
            'sn' => [
                'name_en' => 'Shona',
                'name' => 'chiShona',
                'alpha2' => 'sn',
                'alpha3' => 'sna',
            ],
            'si' => [
                'name_en' => 'Sinhala , Sinhalese',
                'name' => 'සිංහල',
                'alpha2' => 'si',
                'alpha3' => 'sin',
            ],
            'sk' => [
                'name_en' => 'Slovak',
                'name' => 'Slovenčina, Slovenský jazyk',
                'alpha2' => 'sk',
                'alpha3' => 'slk',
            ],
            'sl' => [
                'name_en' => 'Slovenian',
                'name' => 'Slovenski jezik, Slovenščina',
                'alpha2' => 'sl',
                'alpha3' => 'slv',
            ],
            'so' => [
                'name_en' => 'Somali',
                'name' => 'Soomaaliga, af Soomaali',
                'alpha2' => 'so',
                'alpha3' => 'som',
            ],
            'st' => [
                'name_en' => 'Southern Sotho',
                'name' => 'Sesotho',
                'alpha2' => 'st',
                'alpha3' => 'sot',
            ],
            'es' => [
                'name_en' => 'Spanish',
                'name' => 'Español',
                'alpha2' => 'es',
                'alpha3' => 'spa',
            ],
            'su' => [
                'name_en' => 'Sundanese',
                'name' => 'Basa Sunda',
                'alpha2' => 'su',
                'alpha3' => 'sun',
            ],
            'sw' => [
                'name_en' => 'Swahili',
                'name' => 'Kiswahili',
                'alpha2' => 'sw',
                'alpha3' => 'swa',
            ],
            'ss' => [
                'name_en' => 'Swati',
                'name' => 'SiSwati',
                'alpha2' => 'ss',
                'alpha3' => 'ssw',
            ],
            'sv' => [
                'name_en' => 'Swedish',
                'name' => 'Svenska',
                'alpha2' => 'sv',
                'alpha3' => 'swe',
            ],
            'ta' => [
                'name_en' => 'Tamil',
                'name' => 'தமிழ்',
                'alpha2' => 'ta',
                'alpha3' => 'tam',
            ],
            'te' => [
                'name_en' => 'Telugu',
                'name' => 'తెలుగు',
                'alpha2' => 'te',
                'alpha3' => 'tel',
            ],
            'tg' => [
                'name_en' => 'Tajik',
                'name' => 'тоҷикӣ , toçikī , تاجیکی ‎',
                'alpha2' => 'tg',
                'alpha3' => 'tgk',
            ],
            'th' => [
                'name_en' => 'Thai',
                'name' => 'ไทย',
                'alpha2' => 'th',
                'alpha3' => 'tha',
            ],
            'ti' => [
                'name_en' => 'Tigrinya',
                'name' => 'ትግርኛ',
                'alpha2' => 'ti',
                'alpha3' => 'tir',
            ],
            'bo' => [
                'name_en' => 'Tibetan',
                'name' => 'བོད་ཡིག',
                'alpha2' => 'bo',
                'alpha3' => 'bod',
            ],
            'tk' => [
                'name_en' => 'Turkmen',
                'name' => 'Türkmen, Түркмен',
                'alpha2' => 'tk',
                'alpha3' => 'tuk',
            ],
            'tl' => [
                'name_en' => 'Tagalog',
                'name' => 'Wikang Tagalog',
                'alpha2' => 'tl',
                'alpha3' => 'tgl',
            ],
            'tn' => [
                'name_en' => 'Tswana',
                'name' => 'Setswana',
                'alpha2' => 'tn',
                'alpha3' => 'tsn',
            ],
            'to' => [
                'name_en' => 'Tonga (Tonga Islands)',
                'name' => 'Faka Tonga',
                'alpha2' => 'to',
                'alpha3' => 'ton',
            ],
            'tr' => [
                'name_en' => 'Turkish',
                'name' => 'Türkçe',
                'alpha2' => 'tr',
                'alpha3' => 'tur',
            ],
            'ts' => [
                'name_en' => 'Tsonga',
                'name' => 'Xitsonga',
                'alpha2' => 'ts',
                'alpha3' => 'tso',
            ],
            'tt' => [
                'name_en' => 'Tatar',
                'name' => 'татар теле , tatar tele',
                'alpha2' => 'tt',
                'alpha3' => 'tat',
            ],
            'tw' => [
                'name_en' => 'Twi',
                'name' => 'Twi',
                'alpha2' => 'tw',
                'alpha3' => 'twi',
            ],
            'ty' => [
                'name_en' => 'Tahitian',
                'name' => 'Reo Tahiti',
                'alpha2' => 'ty',
                'alpha3' => 'tah',
            ],
            'ug' => [
                'name_en' => 'Uighur , Uyghur',
                'name' => 'ئۇيغۇرچە ‎, Uyghurche',
                'alpha2' => 'ug',
                'alpha3' => 'uig',
            ],
            'uk' => [
                'name_en' => 'Ukrainian',
                'name' => 'Українська',
                'alpha2' => 'uk',
                'alpha3' => 'ukr',
            ],
            'ur' => [
                'name_en' => 'Urdu',
                'name' => 'اردو',
                'alpha2' => 'ur',
                'alpha3' => 'urd',
            ],
            'uz' => [
                'name_en' => 'Uzbek',
                'name' => 'Oʻzbek , Ўзбек , أۇزبېك ‎',
                'alpha2' => 'uz',
                'alpha3' => 'uzb',
            ],
            've' => [
                'name_en' => 'Venda',
                'name' => 'Tshivenḓa',
                'alpha2' => 've',
                'alpha3' => 'ven',
            ],
            'vi' => [
                'name_en' => 'Vietnamese',
                'name' => 'Tiếng Việt',
                'alpha2' => 'vi',
                'alpha3' => 'vie',
            ],
            'vo' => [
                'name_en' => 'Volapük',
                'name' => 'Volapük',
                'alpha2' => 'vo',
                'alpha3' => 'vol',
            ],
            'wa' => [
                'name_en' => 'Walloon',
                'name' => 'Walon',
                'alpha2' => 'wa',
                'alpha3' => 'wln',
            ],
            'cy' => [
                'name_en' => 'Welsh',
                'name' => 'Cymraeg',
                'alpha2' => 'cy',
                'alpha3' => 'cym',
            ],
            'wo' => [
                'name_en' => 'Wolof',
                'name' => 'Wollof',
                'alpha2' => 'wo',
                'alpha3' => 'wol',
            ],
            'fy' => [
                'name_en' => 'Western Frisian',
                'name' => 'Frysk',
                'alpha2' => 'fy',
                'alpha3' => 'fry',
            ],
            'xh' => [
                'name_en' => 'Xhosa',
                'name' => 'isiXhosa',
                'alpha2' => 'xh',
                'alpha3' => 'xho',
            ],
            'yi' => [
                'name_en' => 'Yiddish',
                'name' => 'ייִדיש',
                'alpha2' => 'yi',
                'alpha3' => 'yid',
            ],
            'yo' => [
                'name_en' => 'Yoruba',
                'name' => 'Yorùbá',
                'alpha2' => 'yo',
                'alpha3' => 'yor',
            ],
            'za' => [
                'name_en' => 'Zhuang , Chuang',
                'name' => 'Saɯ cueŋƅ, Saw cuengh',
                'alpha2' => 'za',
                'alpha3' => 'zha',
            ],
            'zu' => [
                'name_en' => 'Zulu',
                'name' => 'isiZulu',
                'alpha2' => 'zu',
                'alpha3' => 'zul',
            ],
        ],
        'alpha3' => [
            'abk' => 'ab',
            'aar' => 'aa',
            'afr' => 'af',
            'aka' => 'ak',
            'sqi' => 'sq',
            'alb' => 'sq',
            'amh' => 'am',
            'ara' => 'ar',
            'arg' => 'an',
            'hye' => 'hy',
            'arm' => 'hy',
            'asm' => 'as',
            'ava' => 'av',
            'ave' => 'ae',
            'aym' => 'ay',
            'aze' => 'az',
            'bam' => 'bm',
            'bak' => 'ba',
            'eus' => 'eu',
            'baq' => 'eu',
            'bel' => 'be',
            'ben' => 'bn',
            'bih' => 'bh',
            'bis' => 'bi',
            'bos' => 'bs',
            'bre' => 'br',
            'bul' => 'bg',
            'mya' => 'my',
            'bur' => 'my',
            'cat' => 'ca',
            'cha' => 'ch',
            'che' => 'ce',
            'nya' => 'ny',
            'zho' => 'zh',
            'chi' => 'zh',
            'chv' => 'cv',
            'cor' => 'kw',
            'cos' => 'co',
            'cre' => 'cr',
            'hrv' => 'hr',
            'ces' => 'cs',
            'cze' => 'cs',
            'dan' => 'da',
            'div' => 'dv',
            'nld' => 'nl',
            'dut' => 'nl',
            'dzo' => 'dz',
            'eng' => 'en',
            'epo' => 'eo',
            'est' => 'et',
            'ewe' => 'ee',
            'fao' => 'fo',
            'fij' => 'fj',
            'fin' => 'fi',
            'fra' => 'fr',
            'fre' => 'fr',
            'ful' => 'ff',
            'glg' => 'gl',
            'kat' => 'ka',
            'geo' => 'ka',
            'deu' => 'de',
            'ger' => 'de',
            'ell' => 'el',
            'gre' => 'el',
            'grn' => 'gn',
            'guj' => 'gu',
            'hat' => 'ht',
            'hau' => 'ha',
            'heb' => 'he',
            'her' => 'hz',
            'hin' => 'hi',
            'hmo' => 'ho',
            'hun' => 'hu',
            'ina' => 'ia',
            'ind' => 'id',
            'ile' => 'ie',
            'gle' => 'ga',
            'ibo' => 'ig',
            'ipk' => 'ik',
            'ido' => 'io',
            'isl' => 'is',
            'ice' => 'is',
            'ita' => 'it',
            'iku' => 'iu',
            'jpn' => 'ja',
            'jav' => 'jv',
            'kal' => 'kl',
            'kan' => 'kn',
            'kau' => 'kr',
            'kas' => 'ks',
            'kaz' => 'kk',
            'khm' => 'km',
            'kik' => 'ki',
            'kin' => 'rw',
            'kir' => 'ky',
            'kom' => 'kv',
            'kon' => 'kg',
            'kor' => 'ko',
            'kur' => 'ku',
            'kua' => 'kj',
            'lat' => 'la',
            'ltz' => 'lb',
            'lug' => 'lg',
            'lim' => 'li',
            'lin' => 'ln',
            'lao' => 'lo',
            'lit' => 'lt',
            'lub' => 'lu',
            'lav' => 'lv',
            'glv' => 'gv',
            'mkd' => 'mk',
            'mac' => 'mk',
            'mlg' => 'mg',
            'msa' => 'ms',
            'may' => 'ms',
            'mal' => 'ml',
            'mlt' => 'mt',
            'mri' => 'mi',
            'mao' => 'mi',
            'mar' => 'mr',
            'mah' => 'mh',
            'mon' => 'mn',
            'nau' => 'na',
            'nav' => 'nv',
            'nde' => 'nd',
            'nep' => 'ne',
            'ndo' => 'ng',
            'nob' => 'nb',
            'nno' => 'nn',
            'nor' => 'no',
            'iii' => 'ii',
            'nbl' => 'nr',
            'oci' => 'oc',
            'oji' => 'oj',
            'chu' => 'cu',
            'orm' => 'om',
            'ori' => 'or',
            'oss' => 'os',
            'pan' => 'pa',
            'pli' => 'pi',
            'fas' => 'fa',
            'per' => 'fa',
            'pol' => 'pl',
            'pus' => 'ps',
            'por' => 'pt',
            'que' => 'qu',
            'roh' => 'rm',
            'run' => 'rn',
            'ron' => 'ro',
            'rum' => 'ro',
            'rus' => 'ru',
            'san' => 'sa',
            'srd' => 'sc',
            'snd' => 'sd',
            'sme' => 'se',
            'smo' => 'sm',
            'sag' => 'sg',
            'srp' => 'sr',
            'gla' => 'gd',
            'sna' => 'sn',
            'sin' => 'si',
            'slk' => 'sk',
            'slo' => 'sk',
            'slv' => 'sl',
            'som' => 'so',
            'sot' => 'st',
            'spa' => 'es',
            'sun' => 'su',
            'swa' => 'sw',
            'ssw' => 'ss',
            'swe' => 'sv',
            'tam' => 'ta',
            'tel' => 'te',
            'tgk' => 'tg',
            'tha' => 'th',
            'tir' => 'ti',
            'bod' => 'bo',
            'tib' => 'bo',
            'tuk' => 'tk',
            'tgl' => 'tl',
            'tsn' => 'tn',
            'ton' => 'to',
            'tur' => 'tr',
            'tso' => 'ts',
            'tat' => 'tt',
            'twi' => 'tw',
            'tah' => 'ty',
            'uig' => 'ug',
            'ukr' => 'uk',
            'urd' => 'ur',
            'uzb' => 'uz',
            'ven' => 've',
            'vie' => 'vi',
            'vol' => 'vo',
            'wln' => 'wa',
            'cym' => 'cy',
            'wel' => 'cy',
            'wol' => 'wo',
            'fry' => 'fy',
            'xho' => 'xh',
            'yid' => 'yi',
            'yor' => 'yo',
            'zha' => 'za',
            'zul' => 'zu',
        ],
        'commons' => ['en', 'es', 'zh', 'pt', 'hi', 'ar', 'ru', 'ja', 'fr', 'de'],
    ];

    /**
     * Returns all the languages in the repository.
     *
     * @return Generator Generator yielding instances of Language class
     */
    public static function getAll(): Generator
    {
        foreach (self::$storage['alpha2'] as $record) {
            yield Language::createFromAlpha2($record['alpha2']);
        }
    }

    /**
     * Returns the language record that matches with the given alpha2 code.
     *
     */
    public static function findAlpha2(string $alpha2): array
    {
        if (strlen($alpha2) !== 2) {
            throw new InvalidArgumentException('The given language code has an invalid length.');
        }

        $alpha2 = strtolower($alpha2);

        if (!isset(self::$storage['alpha2'][$alpha2])) {
            throw new InvalidArgumentException('There is no language with the given code.');
        }

        return self::$storage['alpha2'][$alpha2];
    }

    /**
     * Returns the language record that matches with the given alpha3 code.
     *
     */
    public static function findAlpha3(string $alpha3): array
    {
        if (strlen($alpha3) !== 3) {
            throw new InvalidArgumentException('The given code has an invalid length.');
        }

        $alpha3 = strtolower($alpha3);

        if (!isset(self::$storage['alpha3'][$alpha3])) {
            throw new InvalidArgumentException('There is no language with the given code.');
        }

        return self::$storage['alpha2'][self::$storage['alpha3'][$alpha3]];
    }
}
