---
name: build
on: [ push, pull_request ]

jobs:
  test:
    name: Running tests on ${{ matrix.php }} ${{ matrix.composer-flags }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '7.4', '8.0' ]
        composer-flags: [ '' ]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@2.10.0
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2

      - name: Validate composer manifest
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest ${{ matrix.composer-flags }}

      - name: Run tests
        run: composer test
  coverage:
    needs: [ test ]
    name: Publish test coverage to Code Climate
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@2.10.0
        with:
          php-version: '7.4'
          coverage: xdebug
          tools: composer:v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest ${{ matrix.composer-flags }}

      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_REPORTER_ID }}
        with:
          coverageCommand: composer test-coverage